### ISSUE TITLE
不能导入org.apache.hadoop.conf.Configuration

### ISSUE THREAD

**Issue by awoter** [xpleaf/ispider#1]
HBaseUtil类导入 org.apache.hadoop.conf.Configuration 失败，麻烦楼主看下是依赖的版本问题还是pom没提交完整？

**Comment by xpleaf** [comment]
看了一下跟我本地的一致的，你看看你的依赖下载成功没有

**Comment by awoter** [comment]
请问下你本地是哪个jar哈，我试了几个版本都没这个类   奇怪了

**Comment by xpleaf** [comment]
好，我到时发给你。






在 2018-04-25 19:26:11，"pengpan" <notifications@github.com> 写道：


请问下你本地是哪个jar哈，我试了几个版本都没这个类 奇怪了
